---
title: "PPC Baseline"
author: "Andres Potapczynski (ap3635)"
date: "11/25/2018"
output: pdf_document
---

```{r Imports, include=FALSE}
library(rstan)
library(tidyverse)
library(ggplot2)
library(bayesplot)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
knitr::opts_chunk$set(echo = TRUE)
```

```{r Files, include=FALSE}
file <-  '../DBs/core.txt'
file_model_binomial <- '../Analysis/binomial_spatial_base.stan'
```

# Setting the preamble

```{r Load the data, include=FALSE}
data <- read_delim(file = file, delim = '|')

# Sample the data
pct = 1
# pct = 0.1
# pct = 0.01
set.seed(seed = 42)
sample_size = round(pct * nrow(data))
sample <- sample(x = nrow(data), size = sample_size, replace = F)
data = data[sample, ]

## Selecting the relevant columns for the analysis
data_sub <- data %>% dplyr::select(
  state,
  city,
  county,
  zip,
  asset_market_value,
  mar_2_app,
  appraisal_value,
  app_2_inc,
  client_income,
  mar_2_inc,
  age,
  sex_F,
  condition_U,
  y)
summary(data_sub)

geo <- data_sub %>% 
  group_by(state) %>% 
  summarize(
            y_sum = sum(y),
            state_n = n()) %>% 
  ungroup()
```

```{r Prep data for STAN model}
## Inputs for STAN
y = geo$y_sum
Ns = geo$state_n
N = nrow(geo)

data_stan = list(N=N, Ns=Ns, y=y)
```

```{r Run first STAN model, include=FALSE}
sm <- stan_model(file_model_binomial)
sm.binomial = sampling(sm, data=data_stan, iter=1000, chains=4)
```

```{r Print resutls of the binomial regression, echo=FALSE}
print(sm.binomial, 
      pars = c('theta'),
      digits = 2, 
      probs = c(0.025, 0.5, 0.975))
```

```{r Check the max value}
sims <- rstan::extract(sm.binomial)
y_max <- apply(X = sims$y_rep, MARGIN = 1, FUN = max)
```

```{r Plot histogram, message=FALSE, warning=FALSE}
df <- data.frame(y_rep = y_max)
ggplot(df, aes(x=y_rep)) +
  geom_histogram(fill='lightblue',
                 color='black') +
  geom_vline(xintercept = max(y), color='red')
```

```{r Posterior density overlay}
y_rep <- as.matrix(sm.binomial, pars = "y_rep")
ppc_dens_overlay(y = y, y_rep[1:200,])
```

```{r STD, message=FALSE, warning=FALSE}
df <- data.frame(y_rep = apply(X = sims$y_rep, MARGIN = 1, FUN = sd))
ggplot(df, aes(x=y_rep)) +
  geom_histogram(fill='lightblue',
                 color='black') +
  geom_vline(xintercept = sd(y), color='red')
```

```{r}
unit = 20
df <- data.frame(y_rep = sims$y_rep[, unit])
g20 <- ggplot(df, aes(x=y_rep)) +
  geom_histogram(fill='lightblue',
                 color='black',
                 binwidth = 1) +
  geom_vline(xintercept = y[unit], color='red')

unit = 4
df <- data.frame(y_rep = sims$y_rep[, unit])
g4 <- ggplot(df, aes(x=y_rep)) +
  geom_histogram(fill='lightblue',
                 color='black',
                 binwidth = 1) +
  geom_vline(xintercept = y[unit], color='red')

unit = 11
df <- data.frame(y_rep = sims$y_rep[, unit])
g11 <- ggplot(df, aes(x=y_rep)) +
  geom_histogram(fill='lightblue',
                 color='black',
                 binwidth = 4) +
  geom_vline(xintercept = y[unit], color='red')

unit = 9
df <- data.frame(y_rep = sims$y_rep[, unit])
g9 <- ggplot(df, aes(x=y_rep)) +
  geom_histogram(fill='lightblue',
                 color='black',
                 binwidth = 5) +
  geom_vline(xintercept = y[unit], color='red')

gridExtra::grid.arrange(g11, g9, g4, g20, nrow = 2, ncol = 2)
```

asdf