---
title: "Binomial Zero PPCs"
author: "Andres Potapczynski (ap3635)"
output: pdf_document
---

```{r Inputs, include=FALSE}
library(rstan)
library(tidyverse)
library(ggplot2)
library(arm)
library(bayesplot)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
knitr::opts_chunk$set(echo = TRUE)
source('../Utils/processing.R')
```

```{r Set the parameters, message=FALSE, warning=FALSE}
file <-  '../DBs/city_st.txt'
file_model <- './selected/binomial_zero.stan'
SEED = 1234

CHAINS = 8
ITER = 2000
# CHAINS = 1
# ITER = 20
pct_train = 0.8
pct = 1
# pct = 0.1
# pct = 0.01
comp_sm <- stan_model(file_model)
```

```{r Load the data, message=FALSE, warning=FALSE}
## Load the data
data <- read_delim(file = file, delim = '|')

# Sample the data
data = sample_data(data = data, pct = pct, SEED = SEED)

## Selecting the relevant columns for the analysis
inputs <- data %>% dplyr::select(
  state,
  city,
  client_income,
  # mar_2_inc,
  appraisal_value,
  app_2_inc,
  # asset_market_value,
  mar_2_app,
  sex_F,
  age,
  risk_index,
  employed_30,
  condition_U,
  city_n,
  ID_state,
  y)
summary(inputs)
```

```{r Run the model, include=FALSE}
data_stan = STAN_city(inputs=inputs)

sm = sampling(comp_sm, data=data_stan, iter=ITER, chains=CHAINS)
```

```{r Print the results of the model}
print(sm,
      pars = c('theta', 'alpha', 'beta'),
      digits = 2, 
      probs = c(0.025, 0.5, 0.975))
```

```{r Tail distribution, message=FALSE, warning=FALSE}
sims <- rstan::extract(sm)
T_rep <- apply(X = sims$y_rep, MARGIN = 1, FUN = sum)
T_obs <- sum(inputs$y)
df = data.frame(T_rep=T_rep)
ggplot(df, aes(x=T_rep)) +
  geom_histogram(fill='lightblue',
                 color='black') +
  geom_vline(xintercept = T_obs, color = 'red') +
  ylab('') +
  xlab('Total Defaults') +
  ggtitle('The model correctly captures the total number of defaults')
```

```{r PPC density overlay, warning=FALSE, message=FALSE}
y_rep <- as.matrix(sm, pars = "y_rep")
mask <- inputs$y > 0
g_overlay <- ppc_dens_overlay(y = inputs$y[mask], yrep = y_rep[1:200, mask]) + xlim(0, 20)
g_overlay
```
